name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.10"

      - name: "Set up Python"
        run: uv python install

      - name: "Install the project and dependencies"
        run: uv sync --locked --all-extras --dev

      - name: "Run linters"
        run: |
          uv run isort --check --profile black typeid/ tests/
          uv run flake8 --exit-zero typeid/ tests/ --exit-zero
          uv run black --check --diff typeid/ tests/ --line-length 119
          uv run mypy typeid/ --pretty

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.10"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest -v
